Types and operators hw
mspokrovsk/_TMS_AQAC05 pull request #2
Opened 2023-11-18 11:05 UTC by mspokrovsk

2023-11-20 21:19 UTC, wildpioneer requested changes

2023-11-20 21:19 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +    Console.WriteLine("Число входит в промежуток [-40, -10]");
Отсутствует проверка что введенное число в промежутке от -50 до 50

2023-11-20 21:19 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +/*string[] word = {"отличная", "ужасная", "приятная", "переменчивая", "неустойчивая", "чудесная", "суровая", "непредсказуемая", "отвратительная", "мерзкая" };
Хитрим - к этой домашку мы о массивах еще ничего не знали - ну пойдет ;)

2023-11-20 21:19 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +Console.Write("Введите число: ");
Не надо второй раз вводить число - мы же можем второй способ применить и с уже введенным числом

2023-11-21 02:57 UTC, mspokrovsk commented on TypesAndOperators/Program.cs
> +    Console.WriteLine("Число входит в промежуток [-40, -10]");
Добавила проверку на строку 75

2023-11-21 03:00 UTC, mspokrovsk commented on TypesAndOperators/Program.cs
> +/*string[] word = {"отличная", "ужасная", "приятная", "переменчивая", "неустойчивая", "чудесная", "суровая", "непредсказуемая", "отвратительная", "мерзкая" };
Ниже я написала, что пробовала практиковать)

2023-11-21 03:02 UTC, mspokrovsk commented on TypesAndOperators/Program.cs
> +Console.Write("Введите число: ");
Это задание нужно переделать?

2023-11-27 17:38 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +Console.Write("Введите число: ");
Нет

2023-11-27 17:39 UTC, closed without merging