ADD HW
mspokrovsk/_TMS_AQAC05 pull request #3
Opened 2023-11-25 17:27 UTC by mspokrovsk

2023-11-27 17:56 UTC, wildpioneer requested changes

2023-11-27 17:56 UTC, wildpioneer commented on ArraysAndCycles/Program.cs
> +/*//int[] array = { 1, 9, 3, 6, 5 };
Отсутствует ArraysAndCycles.csproj файл в репозитории - поэтому не могу открыть этот проект у себя и проверить на запуск. Добавь пожалуйста

2023-11-27 17:56 UTC, wildpioneer commented on ArraysAndCycles/Program.cs
> +foreach (int number in numbers)
Перед foreach нужна пустая строка для лучшего чтения кода

2023-11-27 17:56 UTC, wildpioneer commented on ArraysAndCycles/Program.cs
> +Console.Write("Введите число для поиска: ");
До ввода значения лучше всего вывести исходный массив на экран, а то не понятно что именно он содержит.

2023-11-27 17:56 UTC, wildpioneer commented on ArraysAndCycles/Program.cs
> +Console.Write("Введите число для удаления: ");
До ввода значения лучше всего вывести исходный массив на экран, а то не понятно что именно он содержит.

2023-11-27 17:56 UTC, wildpioneer commented on ArraysAndCycles/Program.cs
> +if (count > 0)
Лучше сделать эту проверку до переноса значений в новый массив (строка 298), 
потому что если числа нет - то можно использовать modifiedNumbers = numbers;

2023-11-28 14:16 UTC, mspokrovsk commented on ArraysAndCycles/Program.cs
> +/*//int[] array = { 1, 9, 3, 6, 5 };
Добавила проект

2023-11-28 14:44 UTC, mspokrovsk commented on ArraysAndCycles/Program.cs
> +Console.Write("Введите число для поиска: ");
Добавила

2023-11-28 14:44 UTC, mspokrovsk commented on ArraysAndCycles/Program.cs
> +foreach (int number in numbers)
Добавила пустую строку

2023-12-11 13:54 UTC, wildpioneer commented
Проверено

2023-12-11 13:54 UTC, closed without merging