Add HW
mspokrovsk/_TMS_AQAC05 pull request #4
Opened 2023-11-25 18:49 UTC by mspokrovsk

2023-11-27 17:59 UTC, wildpioneer requested changes

2023-11-27 17:59 UTC, wildpioneer commented on String/Program.cs
> +                    //Console.WriteLine(resultString);
Старайся не оставлять закомментированные строки в PR без надобности

2023-11-27 17:59 UTC, wildpioneer commented on String/Program.cs
> +            Console.WriteLine("\"Welcome\" " + "\"to\" " + "\"the\" " + "\"TMS\" " + "\"lessons\"");
Как вариант. Но хотелось бы увидеть более продвинутые варианты с JOIN или Concat.

2023-11-28 14:54 UTC, mspokrovsk commented on String/Program.cs
> +                    //Console.WriteLine(resultString);
Прошу прощения, по невнимательности

2023-12-11 13:55 UTC, wildpioneer commented
Проверено

2023-12-11 13:55 UTC, closed without merging